[[redirects]]
  from = "/i/static/*"
  to = "https://eu-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/i/*"
  to = "https://eu.i.posthog.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/i/decide"
  to = "https://eu.i.posthog.com/decide"
  status = 200
  force = true
